apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  googleCloudBuild:
    projectId: flickswipe-dev

  artifacts:
    - image: us.gcr.io/flickswipe-dev/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/***/*.ts"
            dest: .
    - image: us.gcr.io/flickswipe-dev/survey
      context: survey
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/***/*.ts"
            dest: .
    - image: us.gcr.io/flickswipe-dev/ingest
      context: ingest
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/***/*.ts"
            dest: .
    - image: us.gcr.io/flickswipe-dev/mail
      context: mail
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/***/*.ts"
            dest: .
    - image: us.gcr.io/flickswipe-dev/predict
      context: predict
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/***/*.ts"
            dest: .
    - image: us.gcr.io/flickswipe-dev/user
      context: user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/***/*.ts"
            dest: .
