apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingest
  template:
    metadata:
      labels:
        app: ingest
    spec:
      containers:
        - name: ingest
          image: us.gcr.io/flickswipe-dev/ingest
          env:
            - name: SENTRY_DSN
              value: "https://8e31546b892c442cb87836185989347d@o485399.ingest.sentry.io/5545304"
            - name: RAPIDAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: rapidapi-secret
                  key: RAPIDAPI_KEY
            - name: TMDB_KEY
              valueFrom:
                secretKeyRef:
                  name: tmdb-secret
                  key: TMDB_KEY
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: flickswipe
            - name: INGEST_DB_USER
              valueFrom:
                secretKeyRef:
                  name: ingest-db-user
                  key: INGEST_DB_USER
                  optional: true
            - name: INGEST_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ingest-db-pass
                  key: INGEST_DB_PASS
                  optional: true
            - name: MONGO_URI
              value: "mongodb+srv://flickswipe-mongodb-clus.v6qxz.mongodb.net"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: DB_USER
                  optional: true
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-pass
                  key: DB_PASS
                  optional: true
