apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingest
  template:
    metadata:
      labels:
        app: ingest
    spec:
      containers:
        - name: ingest
          image: us.gcr.io/flickswipe-dev/ingest
          env:
            - name: SENTRY_DSN
              value: "https://8e31546b892c442cb87836185989347d@o485399.ingest.sentry.io/5545304"
            - name: RAPIDAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: rapidapi-secret
                  key: RAPIDAPI_KEY
            - name: TMDB_KEY
              valueFrom:
                secretKeyRef:
                  name: tmdb-secret
                  key: TMDB_KEY
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: flickswipe
            - name: MONGO_URI
              value: "mongodb+srv://flickswipe:Ey0lpzpKoFhRq5bq@flickswipe-mongodb-clus.v6qxz.mongodb.net/ingest"
