apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predict
  template:
    metadata:
      labels:
        app: predict
    spec:
      containers:
        - name: predict
          image: us.gcr.io/flickswipe-dev/predict
          env:
            - name: SENTRY_DSN
              value: "https://2e5df7e90a74465896fbdb45842c390c@o485399.ingest.sentry.io/5545308"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: flickswipe
            - name: PREDICT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: predict-db-user
                  key: PREDICT_DB_USER
                  optional: true
            - name: PREDICT_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: predict-db-pass
                  key: PREDICT_DB_PASS
                  optional: true
            - name: MONGO_URI
              value: "mongodb+srv://flickswipe-mongodb-clus.v6qxz.mongodb.net"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: DB_USER
                  optional: true
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-pass
                  key: DB_PASS
                  optional: true
            - name: QUEUE_GROUP_NAME
              value: "predict_queue_group"
