apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey
  template:
    metadata:
      labels:
        app: survey
    spec:
      containers:
        - name: survey
          image: us.gcr.io/flickswipe-dev/survey
          env:
            - name: SENTRY_DSN
              value: "https://3223e4cfb05948b180e782a76950f503@o485399.ingest.sentry.io/5545311"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: flickswipe
            - name: SURVEY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: survey-db-user
                  key: SURVEY_DB_USER
                  optional: true
            - name: SURVEY_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: survey-db-pass
                  key: SURVEY_DB_PASS
                  optional: true
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: DB_USER
                  optional: true
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-pass
                  key: DB_PASS
                  optional: true
            - name: MONGO_URI
              value: "mongodb+srv://flickswipe-mongodb-clus.v6qxz.mongodb.net"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: PORT
              value: "3000"
            - name: QUEUE_GROUP_NAME
              value: "survey_queue_group"
---
apiVersion: v1
kind: Service
metadata:
  name: survey-srv
spec:
  selector:
    app: survey
  ports:
    - name: survey
      protocol: TCP
      port: 3000
      targetPort: 3000
