apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey
  template:
    metadata:
      labels:
        app: survey
    spec:
      containers:
        - name: survey
          image: flickswipe/survey
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: flickswipe
            - name: MONGO_URI
              value: "mongodb://survey-mongo-srv:27017/survey"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: PORT
              value: "3000"
            - name: QUEUE_GROUP_NAME
              value: "survey_queue_group"
---
apiVersion: v1
kind: Service
metadata:
  name: survey-srv
spec:
  selector:
    app: survey
  ports:
    - name: survey
      protocol: TCP
      port: 3000
      targetPort: 3000
