apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: us.gcr.io/flickswipe-dev/user
          env:
            - name: SENTRY_DSN
              value: "https://00e0177de713478282e1f0ed74ee207b@o485399.ingest.sentry.io/5545312"
            - name: SENTRY_SAMPLE_RATE
              value: "0"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: flickswipe
            - name: USER_DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-user
                  key: USER_DB_USER
                  optional: true
            - name: USER_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: user-db-pass
                  key: USER_DB_PASS
                  optional: true
            - name: MONGO_URI
              value: "mongodb+srv://flickswipe-mongodb-clus.v6qxz.mongodb.net"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: DB_USER
                  optional: true
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-pass
                  key: DB_PASS
                  optional: true
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: PORT
              value: "3000"
            - name: QUEUE_GROUP_NAME
              value: "user_queue_group"
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 3000
      targetPort: 3000
