name: tests-mail

on:
  pull_request:
    paths:
      - "mail/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd mail && npm install && npm run test:ci
