name: tests-survey

on:
  pull_request:
    paths:
      - "survey/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd survey && npm install && npm run test:ci
