name: tests-ingest

on:
  pull_request:
    paths:
      - "ingest/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ingest && npm install && npm run test:ci
