name: tests-catalog

on:
  pull_request:
    paths:
      - "catalog/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd catalog && npm install && npm run test:ci
